export const projectsData = [
  {
    title: "Remote Lab",
    description: "Remote lab access for users to control the IE Robotics Lab robots from anywhere in the world.",
    imageUrl: "public/remotelab.png",
    link: "https://github.com/IE-Robotics-Lab/remote_lab",
    tmuxname: "remotelab",
    icons: {
      ROS: "public/ros.svg",
      Docker: "public/docker.svg",
      Python: "public/python.svg",
      Opencv: "public/opencv.svg",
      Tensorflow: "public/tensorflow.svg",
    },
  },
  {
    title: "X++ Assistant",
    description: "Extremely proficient coding assistant for the obscure X++ language in Dynamics 365 Finance and Operations. Currently deployed at Dynamics Innovations.",
    imageUrl: "public/xppcoder.png",
    link: "https://github.com/haxybaxy/xppcoder",
    tmuxname: "xppcoder",
    icons: {
      Python: "public/python.svg",
      Langchain: "public/langchain.svg",
      Huggingface: "public/huggingface.svg",
      Pinecone: "public/pinecone.svg",
    },
  },
  {
    title: "EC Language",
    description: "Bytecode interpreter for custom programming language with dynamic typing and garbage collection, written in C.",
    imageUrl: "public/eclang.png",
    link: "https://github.com/haxybaxy/ec-lang",
    tmuxname: "eclang",
    icons: {
      C: "public/c.svg",
      CMake: "public/cmake.svg",
    },
  },
  {
    title: "AI Hackathon 2023",
    description: "Won runner-up with 96% accuracy in the IEU Hackathon 2023 which required building LLM application to extract financial data from various term sheets.",
    imageUrl: "public/aihackathon.jpeg",
    link: "https://github.com/haxybaxy/aihackathon2023",
    tmuxname: "aihackathon",
    icons: {
      Python: "public/python.svg",
      Langchain: "public/langchain.svg",
      OpenAI: "public/openai.svg",
      Pandas: "public/pandas.svg",
    },
  },
  {
    title: "IE Robotics Club Website",
    description: "IE Robotics Club website built with Astro.js and MongoDB.",
    imageUrl: "public/ierobotics.png",
    link: "https://github.com/IERoboticsClub/club_website_v0",
    tmuxname: "clubwebsite",
    icons: {
      React: "public/react.svg",
      Astro: "public/astro.svg",
      Nodejs: "public/nodejs.svg",
      Express: "public/express.svg",
      Mongodb: "public/mongodb.svg",
      Docker: "public/docker.svg",
    },
  },
];
