export const projectsData = [
  {
    title: "Launchyfi",
    description: "World's first AI GTM Engineer. Aims to link outreach tools, enrichment tools and CRMs autonomously.",
    imageUrl: "/projectphotos/launchyfi.png",
    category: "Startups",
    link: "https://launchyfi.com",
    tmuxname: "launchyfi",
    icons: {
      "Next.js": "/icons/nextjs.svg",
      Supabase: "/icons/supabase.svg",
      Python: "/icons/python.svg",
      FastAPI: "/icons/fastapi.svg",
      Langgraph: "/icons/langgraph.svg",
      Pinecone: "/icons/pinecone.svg",
    },
  },
  {
    title: "Holla at Your Boy",
    description: "Github action to tag your coworkers with code comments.",
    imageUrl: "/projectphotos/holla.png",
    category: "Dev Tools",
    github: "https://github.com/haxybaxy/holla-at-your-boy",
    tmuxname: "holla-at-your-boy",
    icons: {
      "Github Actions": "/icons/github.svg",
    },
  },
  {
    title: "Search Preview",
    description: "VSCode Extension to mimic file searching with Telescope in Neovim.",
    imageUrl: "/projectphotos/searchpreview.png",
    category: "Dev Tools",
    github: "https://github.com/haxybaxy/search-preview",
    tmuxname: "searchpreview",
    icons: {
      Typescript: "/icons/typescript.svg",
    },
  },
  {
    title: "ClearSplit",
    description: "Financial tooling for property managers.",
    imageUrl: "/projectphotos/clearsplit.png",
    category: "Startups",
    link: "https://clearsplit.io",
    tmuxname: "remotelab",
    icons: {
      React: "/icons/react.svg",
      Supabase: "/icons/supabase.svg",
      Langchain: "/icons/langchain.svg",
    },
  },
  {
    title: "Worktap!",
    description: "Job board for short term gigs.",
    imageUrl: "/projectphotos/worktap.png",
    category: "Startups",
    link: "https://www.worktap.info/",
    tmuxname: "remotelab",
    icons: {
      Expo: "/icons/expo.svg",
      "React Native": "/icons/react.svg",
      Typescript: "/icons/typescript.svg",
      Firebase: "/icons/firebase.svg",
    },
  },
  {
    title: "Distributed Stock Market Prediction",
    description: "LSTM Network that syncs its weights across multiple nodes to predict stock prices. Done for High Performance Computing course. I know the video isn't 4K 1440p, I didn't have enough storage space to render with a higher quality 😭.",
    imageUrl: "/projectphotos/hpc.jpeg",
    category: "University Projects",
    github: "https://github.com/haxybaxy/hpc-stock-prediction",
    link:"https://www.youtube.com/watch?v=bE9OQoD-mg0",
    tmuxname: "hpc-stock-prediction",
    icons: {
      Python: "/icons/python.svg",
      Tensorflow: "/icons/tensorflow.svg",
      Cuda: "/icons/cuda.svg",
    },
  },
  {
    title: "DeployPilot",
    description: "Prototype for Agentic AI System that can deploy any code on any machine using various MCPs. Done for Recommenders Systems and Chatbots course.",
    imageUrl: "/projectphotos/deploypilot.png",
    category: "University Projects",
    github: "https://github.com/IE-Robotics-Lab/remote_lab",
    link: "https://www.youtube.com/watch?v=II6IIS46uPw",
    tmuxname: "remotelab",
    icons: {
      ROS: "/icons/ros.svg",
      Docker: "/icons/docker.svg",
      Python: "/icons/python.svg",
      OpenCV: "/icons/opencv.svg",
      Tensorflow: "/icons/tensorflow.svg",
    },
  },
  {
    title: "Gaze Tracker",
    description: "Gaze Tracker project for my Computer Vision Course.",
    imageUrl: "/projectphotos/gazetracker.jpeg",
    category: "University Projects",
    github: "https://github.com/haxybaxy/eyetracker",
    link: "https://www.youtube.com/watch?v=JJY0FWCcJ8g",
    tmuxname: "remotelab",
    icons: {
      Python: "/icons/python.svg",
      OpenCV: "/icons/opencv.svg",
    },
  },
  {
    title: "FitWave",
    description: "App for personal trainers made by personal trainers. My first startup (it didn't work out).",
    imageUrl: "/projectphotos/fitwave.jpg",
    category: "Startups",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7273049653883924481/",
    tmuxname: "remotelab",
    icons: {
      Expo: "/icons/expo.svg",
      Typescript: "/icons/typescript.svg",
      ReactNative: "/icons/react.svg",
      Firebase: "/icons/firebase.svg",
      Python: "/icons/python.svg",
      Langchain: "/icons/langchain.svg",
      Pinecone: "/icons/pinecone.svg",
    },
  },
  {
    title: "Remote Lab",
    description: "Remote Lab access for users to control the IE Robotics Lab robots from anywhere in the world. Contains ROS package for ArUco tag detection with OpenCV and syncs coordinates with OptiTrack System",
    imageUrl: "/projectphotos/remotelab.png",
    category: "Professional Projects",
    github: "https://github.com/IE-Robotics-Lab/remote_lab",
    tmuxname: "remotelab",
    icons: {
      ROS: "/icons/ros.svg",
      Docker: "/icons/docker.svg",
      Python: "/icons/python.svg",
      OpenCV: "/icons/opencv.svg",
      Tensorflow: "/icons/tensorflow.svg",
    },
  },
  {
    title: "X++ Assistant",
    description: "Extremely proficient coding assistant for the obscure X++ language in Dynamics 365 Finance and Operations. Currently deployed at Dynamics Innovations.",
    imageUrl: "/projectphotos/xppcoder.png",
    category: "Professional Projects",
    github: "https://github.com/haxybaxy/xppcoder",
    tmuxname: "xppcoder",
    icons: {
      Python: "/icons/python.svg",
      Langchain: "/icons/langchain.svg",
      HuggingFace: "/icons/huggingface.svg",
      Pinecone: "/icons/pinecone.svg",
    },
  },
  {
    title: "EC Language",
    description: "Bytecode interpreter for custom programming language with dynamic typing and garbage collection, written in C.",
    imageUrl: "/projectphotos/eclang.png",
    category: "University Projects",
    github: "https://github.com/haxybaxy/ec-lang",
    tmuxname: "eclang",
    icons: {
      C: "/icons/c.svg",
      CMake: "/icons/cmake.svg",
    },
  },
  {
    title: "Monsieur",
    description: "AI Platform that uses ElevenLabs API to provide a managable fleet of virtual front desk employees for hotels. Facilitates phone calls and is able to book rooms and provide services for hotel guests.",
    imageUrl: "/projectphotos/monsieur.jpg",
    category: "Competitions",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7327688977786785793/",
    tmuxname: "monsieur",
    icons: {
      "Next.js": "/icons/nextjs.svg",
      Langgraph: "/icons/langgraph.svg",
      FastAPI: "/icons/fastapi.svg",
      Supabase: "/icons/supabase.svg",
    },
  },
  {
    title: "Agentic Investment Tracker",
    description: "Tracknetic is a toolkit designed to help Venture Capitalists and Investors to find new investments in different fields, and keep tabs on notable technologies, companies, people and more, using AI Agents that you can dispatch tasks to conversationally. Won the IE x OpenAI Use Case Showcase Competition.",
    imageUrl: "/projectphotos/tracknetic.jpg",
    category: "Competitions",
    link: "https://www.linkedin.com/feed/update/urn:li:activity:7332082469791227905/",
    tmuxname: "tracknetic",
    icons: {
      React: "/icons/react.svg",
      Langchain: "/icons/langchain.svg",
      Langgraph: "/icons/langgraph.svg",
    },
  },
  {
    title: "AI Hackathon 2023",
    description: "Won runner-up with 96% accuracy in the IEU Hackathon 2023 which required building LLM application to extract financial data from various term sheets.",
    imageUrl: "/projectphotos/aihackathon.jpeg",
    category: "Competitions",
    github: "https://github.com/haxybaxy/aihackathon2023",
    tmuxname: "aihackathon",
    icons: {
      Python: "/icons/python.svg",
      Langchain: "/icons/langchain.svg",
      OpenAI: "/icons/openai.svg",
      Pandas: "/icons/pandas.svg",
    },
  },
  {
    title: "IE Robotics Club Website",
    description: "IE Robotics Club website built with Astro.js and MongoDB.",
    category: "University Projects",
    imageUrl: "/projectphotos/ierobotics.png",
    github: "https://github.com/IERoboticsClub/club_website_v0",
    tmuxname: "clubwebsite",
    icons: {
      React: "/icons/react.svg",
      Astro: "/icons/astro.svg",
      "Node.js": "/icons/nodejs.svg",
      "Express.js": "/icons/express.svg",
      MongoDB: "/icons/mongodb.svg",
      Docker: "/icons/docker.svg",
    },
  },
  {
    title: "UNO",
    description: "Pygame adaptation of the classic game Uno for DSA Class.",
    imageUrl: "/projectphotos/uno.png",
    category: "University Projects",
    github: "https://github.com/IERoboticsClub/club_website_v0",
    tmuxname: "clubwebsite",
    icons: {
      React: "/icons/react.svg",
      Astro: "/icons/astro.svg",
      "Node.js": "/icons/nodejs.svg",
      "Express.js": "/icons/express.svg",
      MongoDB: "/icons/mongodb.svg",
      Docker: "/icons/docker.svg",
    },
  },
];
